version: "3.9"

services:
  flavorai-backend:
    build: .
    container_name: flavorai-backend
    ports:
      - "3030:3030"
    depends_on:
      - db
    env_file:
      - .env.docker
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/flavorai
    restart: always

  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: flavorai
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
